import type { Metadata } from "next";
import {GeistSans} from 'geist/font/sans';
import {GeistMono} from 'geist/font/mono';
import { GeistPixelGrid } from 'geist/font/pixel';


import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${GeistMono.variable}
          ${GeistSans.variable} 
          antialiased`}
      >
        {children}
      </body>
    </html>
  );
}